spark.master                     spark://spark-master:7077
spark.eventLog.enabled           true
spark.eventLog.dir               /data/spark-events
spark.sql.shuffle.partitions     200
spark.driver.memory              2g
spark.executor.memory            2g
spark.executor.cores             2
spark.sql.parquet.filterPushdown true
spark.sql.adaptive.enabled       true
spark.sql.adaptive.coalescePartitions.enabled true
